kind: pipeline
type: kubernetes
name: default
steps:
  - name: build
    pull: always
    image: alpine/helm
    commands: 
      - helm lint ./webapp
      - helm package charts/* -d .deploy
trigger:
  branch:
  - main
