kind: pipeline
type: kubernetes
name: default
steps:
  - name: build
    pull: always
    image: alpine/helm
    commands: 
      - helm lint ./webapp
      - helm install webapp ./webapp --dry-run
      - helm package charts/* -d .deploy
